  version: 0.2

  phases:
    install:
      commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

    build:
      commands:
      - export VERSION=$CODEBUILD_SOURCE_VERSION
      - echo "CODEBUILD version $VERSION"
      - echo "Building gmailsmtp Version $CODEBUILD_SOURCE_VERSION"
      - docker build -t 648548064017.dkr.ecr.us-east-1.amazonaws.com/transactrx/gmailsmtp:$VERSION .
      - docker push 648548064017.dkr.ecr.us-east-1.amazonaws.com/transactrx/gmailsmtp:$VERSION
    post_build:
      commands:
        - echo "Build for gmailsmtp completed on `date`"
#  artifacts:
#    files:
#      - Interfaces/target/csinterfaces.war docker/war/.
#      - Jobs/target/*.jar docker/jar/.
#      - Readers/target/*.jar docker/jar/
#    discard-paths: yes
